---

- apt: name=ntp

- service: name=ntp state=stopped

- shell: ntpdate -s time.nist.gov

- service: name=ntp state=started

- copy: src=.ssh/ dest=/home/{{ app_user }}/.ssh/ owner={{ app_user }} mode=0600

