---
- apt_repository: repo='ppa:nginx/stable'

- apt: pkg=nginx update_cache=true

- file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/conf.d/default
    - /etc/nginx/sites-enabled/default

- template: src=site.conf.j2  dest=/etc/nginx/conf.d/site.conf

- service: name=nginx state=reloaded

